컨트랙트 참조를 추가하는 행위가 제대로 작동하는지 테스트해보자.

## 테스트 코드를 작성할 때...

테스트 코드의 로직이 문제인 경우가 아닌, *여러 컨트랙트가 복잡하게 서로 연동하여 작동하는 과정에서 발생하는 충돌* 에 의하여 문제가 발생하는 경우가 있다. `Ganache`를 재시동하거나, `artifact` 파일을 다시 생성하는 등 환경 문제도 항상 염두에 두자.

## Exercise 4: Update Test Code

1. Add a reference to the `App` contract in `config/testConfig.js`
  - `const ExerciseC6CApp = artifacts.require('ExerciseC6CApp')`
2. Create a new instance of the `App` contract in `config/testConfig.js`
  - `let exerciseC6CApp = await ExerciseC6CApp.new(exerciseC6C.address)`
3. Add a reference to the `App` contract instance in the return value in `config/testConfig.js`
  - `exerciseC6CApp: exerciseC6CApp`
4. Change the contract reference for `addSale()` in `test/ExerciseC6C.js`
  - 본래는 `exerciseC6C`를 활용했었다
  - `await config.exerciseC6CApp.addSale(employee.id, 400)`
5. Run `npm test` and ensure that the test passes

## Solution

`App` 컨트랙트를 선언할 때, `Data` 컨트랙트의 주소를 인자로 전달하는 것을 잊지 말자

## Security Between Contracts

- Data contract is assumed to be the controlling contract
- Data contract uses a `function modifier` to check if calling contract is authorized
  - Contract owner *registers and deregisters* calling contract addresses in data contract for assertion by function modifier

`App` 컨트랙트는 `Data` 컨트랙트의 위치(주소)를 알고, 반대로 `Data` 컨트랙트는 `App` 컨트랙트의 주소를 모른다. 호출을 받기만 하는 입장이므로. 하지만 *자신을 호출하는 `App` 컨트랙트가 허가받은 컨트랙트인지는 알 수 있어야 한다*.
